# Copyright (c)  2021  Fangjun Kuang (csukuangfj@gmail.com)

# See ../../LICENSE for clarification regarding multiple authors


name: build-windows-conda

on:
  push:
    branches:
      - conda

env:
  BUILD_TYPE: Release

jobs:
  build-windows-conda:
    # see https://github.com/actions/virtual-environments/blob/win19/20210525.0/images/win/Windows2019-Readme.md
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019]
        # Python 3.9 is for PyTorch 1.7.1, 1.8.0, 1.8.1
        python-version: [3.6, 3.7, 3.8, 3.9]
        torch: ["1.5.0", "1.5.1", "1.6.0", "1.7.0", "1.7.1", "1.8.0", "1.8.1"]
        exclude:
          - python-version: 3.9 # exclude Python 3.9 for [1.5.0, 1.5.1, 1.6.0, 1.7.0]
            torch: "1.5.0"
          - python-version: 3.9
            torch: "1.5.1"
          - python-version: 3.9
            torch: "1.6.0"
          - python-version: 3.9
            torch: "1.7.0"

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          activate-environment: k2

      - name: Install conda dependencies
        shell: bash -l {0}
        run: |
          conda install -y -q anaconda-client
          conda install -y -q conda-build
          conda install -y -q -c pytorch pytorch=${{ matrix.torch }} cpuonly

      - name: Display Python version
        shell: bash -l {0}
        run: |
          python -c "import sys; print(sys.version)"
          which python

      - name: Display conda info
        shell: bash -l {0}
        run: |
          conda env list
          conda info
          which conda
          python --version
          which python
          python -m torch.utils.collect_env

      - name: Build k2
        shell: bash -l {0}
        env:
          K2_PYTHON_VERSION: ${{ matrix.python-version}}
          K2_TORCH_VERSION: ${{ matrix.torch }}
          K2_CONDA_TOKEN: ${{ secrets.K2_CONDA_TOKEN}}
          K2_IS_GITHUB_ACTIONS: 1
          K2_IS_FOR_CONDA: 1
        run: |
          export K2_BUILD_TYPE=Release
          ./scripts/build_conda_cpu.sh

      - name: Display generate results
        shell: bash -l {0}
        run: |
          ls -lh /c/Miniconda/envs/k2/conda-bld
          ls -lh /c/Miniconda/envs/k2/conda-bld/*/*
          ls -lh /c/Miniconda/envs/k2/conda-bld/win-64/*

      - name: Upload Wheel
        uses: actions/upload-artifact@v2
        with:
          name: torch-${{ matrix.torch }}-python-${{ matrix.python-version }}-${{ matrix.os }}-cpu
          path: c:/Miniconda/envs/k2/conda-bld/win-64/*.tar.bz2
